version: '3.1'
services:
  database:
    image: postgres:12.17
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB}
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
